name: Build and release package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and release package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout_repository
        uses: actions/checkout@v4

      - name: Get package version
        id: get_version
        run: |
          PACKAGE_VERSION="$(dpkg-parsechangelog -S Version)"
          echo "package_version=${PACKAGE_VERSION}" >> "$GITHUB_OUTPUT"
          echo "Package version: ${PACKAGE_VERSION}"

      - name: Build package
        id: build_package
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: -us -uc -b

      - name: Publish release
        id: publish_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.get_version.outputs.package_version }}
          name: v${{ steps.get_version.outputs.package_version }}
          artifacts: debian/artifacts/fake-proxmox-subscription_${{ steps.get_version.outputs.package_version }}_all.deb
